//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TirupatiFinance.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Marathi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Marathi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TirupatiFinance.Resource.Marathi", typeof(Marathi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पत्ता.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बाहेर जा.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संपर्क.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संपर्क 1.
        /// </summary>
        internal static string Contact_1 {
            get {
                return ResourceManager.GetString("Contact 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संपर्क 2.
        /// </summary>
        internal static string Contact_2 {
            get {
                return ResourceManager.GetString("Contact 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सभासद.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सभासद क्रमांक.
        /// </summary>
        internal static string Customer_Mobile {
            get {
                return ResourceManager.GetString("Customer Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सभासद नाव.
        /// </summary>
        internal static string Customer_Name {
            get {
                return ResourceManager.GetString("Customer Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दैनिक संग्रह.
        /// </summary>
        internal static string Daily_Collection {
            get {
                return ResourceManager.GetString("Daily Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गॅरेंटर माहिती.
        /// </summary>
        internal static string Guarantor_Information {
            get {
                return ResourceManager.GetString("Guarantor Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गॅरेंटर नाव 1.
        /// </summary>
        internal static string Guarantor_Name_1 {
            get {
                return ResourceManager.GetString("Guarantor Name 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गॅरेंटर नाव 2.
        /// </summary>
        internal static string Guarantor_Name_2 {
            get {
                return ResourceManager.GetString("Guarantor Name 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to हप्त्याची रक्कम.
        /// </summary>
        internal static string Installment_Amount {
            get {
                return ResourceManager.GetString("Installment Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्ज पूर्ण होण्याची तारीख.
        /// </summary>
        internal static string Loan_Completion_Date {
            get {
                return ResourceManager.GetString("Loan Completion Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्ज घेतल्याची तारीख.
        /// </summary>
        internal static string Loan_Taken_Date {
            get {
                return ResourceManager.GetString("Loan Taken Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सभासद माहिती.
        /// </summary>
        internal static string Manage_Customer {
            get {
                return ResourceManager.GetString("Manage Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नवीन सभासद.
        /// </summary>
        internal static string New_Customer {
            get {
                return ResourceManager.GetString("New Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अहवाल.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रीसेट करा.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जतन करा.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एकूण कालावधी.
        /// </summary>
        internal static string Total_Duration {
            get {
                return ResourceManager.GetString("Total Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एकूण कर्जाची रक्कम.
        /// </summary>
        internal static string Total_Loan_Amount {
            get {
                return ResourceManager.GetString("Total Loan Amount", resourceCulture);
            }
        }
    }
}
